title: Aaron Lichtner
email: alichtner@gmail.com
tagline:          'A Jekyll theme'
description: >- # this means to ignore newlines until "baseurl:"

baseurl: ""
url: ""
github_username:  alichtner

# Build settings
markdown: kramdown
plugins: [jekyll-feed, jekyll-paginate]


header_pages:
 - about.md
 - resume.md
 - projects.md
 - contact.md

collections:
  projects:
    output: true

# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty


paginate: 4

