title: Aaron Lichtner
email: alichtner@gmail.com
tagline: 'I like to make stuff'
description: 'I like to make stuff'

baseurl: ""
url: ""
github_username:  alichtner
linkedin_username: aaronlichtner
github_repo: github.com/alichtner.github.io
emailme: mailto:alichtner@gmail.com
instagram_handle: seattlefreezer

# Build settings
markdown: kramdown
plugins: [jekyll-feed, jekyll-paginate]


header_pages:
 - about.md
 - resume.md
 - projects.md
 - contact.md

collections:
  projects:
    output: true

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty


paginate: 4

